### ISSUE TITLE
vertx module not found

### ISSUE THREAD

**Issue by terebentina** [jakearchibald/es6-promise#100]
Getting this when using es6-promise 2.1.0 with webpack-dev-server:
./~/es6-promise/dist/es6-promise.js
Module not found: Error: Cannot resolve module 'vertx' in C:\web\node_modules\es6-promise\dist

**Comment by terebentina** [comment]
@ ./~/es6-promise/dist/es6-promise.js 125:20-30

**Comment by terebentina** [comment]
Just tested, this doesn't happen with 2.0.1

**Comment by MathieuDoyon** [comment]
+1

**Comment by stefanpenner** [comment]
Master works fine. Pending @jakearchibald  for a release

**Comment by jakearchibald** [comment]
There's nothing new to release (there haven't been any commits since 2.1.0)

Looks like `when` had the same issue https://github.com/cujojs/when/pull/366. @stefanpenner should this fix be here or upstream rsvp?

**Comment by stefanpenner** [comment]
#105 fixes it in browserify, I assume web-pack may follow the same conventions here, or maybe just delegate out to browserify.

**Comment by vvo** [comment]
Why is there anything specific to vertx here? Looks weird

**Comment by jakearchibald** [comment]
See https://github.com/jakearchibald/es6-promise/blob/master/lib/es6-promise/asap.js#L90 - some trickery is used to require vertx but prevent browserify detecting it. Seems that webpack isn't fooled by this.

**Comment by stefanpenner** [comment]
I submitted the config option that makes browserify actually ignore it. Maybe web pack also supports something like this?

If no one is sure I can dig in further

**Comment by MathieuDoyon** [comment]
Here's what I added in my webpack config file until the changes are made.

```
plugins: [
    new webpack.IgnorePlugin(/vertx/),
],
```

**Comment by cesarandreu** [comment]
Still screws up with webpack :(. I had to keep `new webpack.IgnorePlugin(/vertx/)` in my plugin list.

**Comment by stefanpenner** [comment]
Is there a config token in package.json webpack cares about?

**Comment by gpbl** [comment]
@stefanpenner `"browser": {  "vertx": false }` does fix the issue with webpack – but the change is not yet released on npm.

**Comment by stefanpenner** [comment]
Ah ok.

@jakearchibald do you mind if I cut a new release( assuming I have all the credentials)

**Comment by jakearchibald** [comment]
Just done a release :dash:

**Comment by jakearchibald** [comment]
@stefanpenner I've added you as an owner, feel free to release at will

**Comment by cesarandreu** [comment]
Awesome, thank you :D. Now it's working as expected.

**Comment by stefanpenner** [comment]
@jakearchibald anything i need to know about the s3 stuff or bower stuff?

**Comment by stefanpenner** [comment]
tracking here: https://github.com/stefanpenner/es6-promise/issues/305
