### ISSUE TITLE
v2.1.0 changelog?

### ISSUE THREAD

**Issue by ljharb** [jakearchibald/es6-promise#107]
I'd love to know what changed in `v2.1.0`, but it appears the changelog isn't updated.

**Comment by ai** [comment]
+1

**Comment by carlsverre** [comment]
+1

**Comment by stefanpenner** [comment]
+1 :trollface:

**Comment by stefanpenner** [comment]
going forward, we will keep this changelog in better sync.

**Comment by ljharb** [comment]
Any way to retroactively add changes for `2.0.1` - `2.3.0`? Without that, I can't upgrade past `2.0` safely (unless I read the entire diff)

**Comment by stefanpenner** [comment]
I would have to also read the diff to construct the change log. It has been to long to remember.
