### ISSUE TITLE
Use native polyfill on Chrome and Node.js v0.12

### ISSUE THREAD

**Issue by piranna** [jakearchibald/es6-promise#111]
On v8 based Javascript engines, [the check for using the native Polyfill implementations](https://github.com/jakearchibald/es6-promise/blob/357b7e7d28c3bc5dadec3aa5c9b58d552b4226f7/dist/es6-promise.js#L933) fails because the check

```Javascript
Object.prototype.toString.call(P.resolve())
```

return ```[object Object]``` instead of the expected ```[object Promise]```, that only happens to be on Firefox. I think this check should be less strict or use other condition so v8 native Promises can be used.

**Comment by yethee** [comment]
And not has the static method `cast`.

**Comment by piranna** [comment]
> And not has the static method cast.

No they don't have it (at least Chromium 41 and Node.js v0.12.2)

**Comment by yethee** [comment]
I mean that the native `Promise` of V8 has no method `cast`.

**Comment by piranna** [comment]
Firefox 37 doesn't have it either...

**Comment by lvscar** [comment]
https://github.com/jakearchibald/es6-promise/pull/99  fixed it  , but not have merged .

**Comment by piranna** [comment]
Definitely a better checker, let's see if it got merged :-)

**Comment by klimashkin** [comment]
```
Object.prototype.toString.call(Promise.resolve())
"[object Object]"
```
Chrome 45.0.2428.0 Canary
V8 4.5.45

Such method seems like suits better:
```
typeof Promise !== "undefined" && Promise.toString().indexOf("[native code]") > -1
```
http://stackoverflow.com/posts/22517133/revisions

**Comment by stefanpenner** [comment]
There are still some serious bugs in the v8 promise implementation.

**Comment by klimashkin** [comment]
Could you give an examples of v8 bugs?

**Comment by stefanpenner** [comment]
It doesn't handle inheritance correctly And resolve isn't correct. Which results in observable ordering differences  https://code.google.com/p/v8/issues/detail?id=4162&q=Promise&colspec=ID%20Type%20Status%20Priority%20Owner%20Summary%20HW%20OS%20Area%20Stars

**Comment by stefanpenner** [comment]
For some reason I can't find the inheritance issue I reported...  Strange I have clear memory of it being responded to as well..

**Comment by stefanpenner** [comment]
found it: https://code.google.com/p/chromium/issues/detail?id=493797

**Comment by koba04** [comment]
I think it would be better to check to be 'thenable' like below.

```js
Promise && typeof new Promise(function() {}).then === 'function'
```

**Comment by stefanpenner** [comment]
> I think it would be better to check to be 'thenable' like below.

but the promise implementations that don't match ^^ have bugs still. Why loosen the constraint, and introduce bugs...

**Comment by NoelAbrahams** [comment]
@stefanpenner, 

I see the point about the couple of bugs in Chrome's implementation. However, they may well fix [the `[object Promise]` bug](https://code.google.com/p/v8/issues/detail?id=3241) before fixing those. Then people will start defaulting to the native implementation without their knowledge.
