### ISSUE TITLE
[Question] Scheduling issue with node ?

### ISSUE THREAD

**Issue by vicb** [jakearchibald/es6-promise#114]
Based on [a comment](https://github.com/jakearchibald/es6-promise/pull/113#issuecomment-97882270) from @jakearchibald.

Jack I had decided to look at the implementation for `setImmediate()` and took an other look at your comment:

```js
setImmediate(_ => console.log(1));
Promise.resolve().then(_ => console.log(2));
setImmediate(_ => console.log(3));
```

>The above will currently log 1,2,3, is the aim of this PR to make it 1,3,2 if zone.js is present? If so, I'm a little worried about it as it breaks es6.

It seems wrong when I looked at it again this morning:
- `setImmediate()` should enqueue on the macrotask queue,
- `.then()` should use the microtask queue,
- the expected result is then "2, 1, 3" - which it is when you executed this code with node 0.12

Now looking at the code again, `asap()` [indeed uses](https://github.com/jakearchibald/es6-promise/blob/16da454c78fde6ff1841d098df0b1ad8a186fb73/lib/es6-promise/asap.js#L33) `setImmediate()` on node 0.10. So when run with node 0.10, the result of

```js
setImmediate(_ => console.log(1));
ES6Promise.Promise.resolve().then(_ => console.log(2));
setImmediate(_ => console.log(3));
```

will be "1, 2, 3" which is not expected.

I'm unsure if there is a better way to enqueue a microtask with Node 0.10 (as `nextTick` could not be used according to the comment).

If I'm right, this looks like an issue of ES6Promise ? _if so it should probably be documented_

edit: some [background info](https://github.com/YuzuJS/setImmediate#processnexttick) on `process.nextTick()` - TL;DR: pre-0.9, it enqueues a macrotask.

**Comment by vicb** [comment]
confirmed via testing the last snippet from the previous comment:
- node 0.10.38 -> "1, 2, 3"
- node 0.12.2 -> "2, 1, 3"

/cc @stefanpenner

**Comment by stefanpenner** [comment]
nextTick on node 0.10 has a serious bug for long chains between two different producers: https://github.com/tildeio/rsvp.js/pull/337

**Comment by vicb** [comment]
Thanks for the reference.

Do we have any other choice than the current implementation ? If not we should at least document that
- with node <= 0.10, scheduling is different from ES6 Promise,
- with node >= 0.11, scheduling is the same as ES6 Promise (they've been introduced in node 0.12),
- if the browser fall-back to `setTimeout()`, scheduling will be different from ES6 Promise.

_(Note that 1 is actually 2 folds, <=0.9 `nextTick` is used but act as latter `setImmediate` (enqueues a macrotask), 0.10 `setImmediate` is used which enqueues a macrotask)_

Should I submit PRs to rsvp / es6-promise adding a "Known issues" section ?

**Comment by stefanpenner** [comment]
> Do we have any other choice than the current implementation ?

We can release a version without the work-around for the node 0.10 problem. In all honesty though node 0.10 is quite old, this problem has literally be fixed upstream for years.

Seems like the bugfix is for people to upgrade to node 0.12 or later

Ultimately, I can be convinced of taking either direction.

**Comment by vicb** [comment]
If we can override the scheduler, we can pick a default behavior and make it easy to override it.

**Comment by vicb** [comment]
We can resolve this one by:
- document the "issue",
- document how to revert to a proper scheduling once #116 is merged by forcing the use of `nextTick` (and warn user about potential issues that come along)

**Comment by stefanpenner** [comment]
> We can resolve this one by:
> 
> document the "issue",
> document how to revert to a proper scheduling once #116 is merged by forcing the use of nextTick (and warn user about potential issues that come along)

sounds good, i may have time later this week.

(thanks for the clear steps to resolve)

**Comment by vicb** [comment]
I could try to draft something (most probably on Friday) but I'm not sure how to be able describe the issue accurately (i.e. interaction between different schedulers).

Anyway, if you fell it could helpful for you to have something to start with/review let me know and I'll prepare this.

**Comment by stefanpenner** [comment]
> If we can override the scheduler, we can pick a default behavior and make it easy to override it.

note:the scheduler is now overridable -> https://github.com/jakearchibald/es6-promise/pull/116

**Comment by vicb** [comment]
My idea was to keep the current behavior and explain to node 10 users how they can update and the limitations

**Comment by stefanpenner** [comment]
> My idea was to keep the current behavior and explain to node 10 users how they can update and the limitations

eeems reasonable.

**Comment by vvo** [comment]
@vicb @stefanpenner What's the workaround for node 0.10 users you are talking about?

**Comment by vicb** [comment]
@vvo with node 0.10 es6-promises uses [setImmediate()](https://github.com/jakearchibald/es6-promise/blob/master/lib/es6-promise/asap.js#L47) because [`nextTick()` has some issues](https://github.com/jakearchibald/es6-promise/issues/114#issuecomment-99456827)

We should indicate to users of this lib how to switch back to using `nextTick()` but warn them about the limitations when doing so.

**Comment by stefanpenner** [comment]
@vicb thinking about this, i wonder if we should just move to nextTick always, and let the failure scenario happens. No other promise lib handles the failure case either.

**Comment by vicb** [comment]
Not sure it's worth breaking BC for older systems ? 
Anyway let me know what you decide and I'll submit a PR.

**Comment by stefanpenner** [comment]
i believe reverting that would merely restore it to be no worse then any other promise lib on that version of node
