### ISSUE TITLE
Promise.all should immediately resolve an empty array

### ISSUE THREAD

**Issue by martynsmith** [jakearchibald/es6-promise#115]
I notice at least the Chrome native Promise object does this, but es6-promise does not?

**Comment by stefanpenner** [comment]
Do you mean synchronously resolve? Or...

**Comment by stefanpenner** [comment]
Chrome 44:

```js
Promise.all([]).then(console.log.bind(console)); console.log("hi")

> 'hi'
> []
```

ES6-Promise
```js
require('es6-promise').Promise.all([]).then(console.log.bind(console)); console.log("hi")

> 'hi'
> []
```

**Comment by martynsmith** [comment]
Hmmm, when I tried your example it worked perfectly, I'll investigate further as to why it didn't appear to be working in my actual code ... thanks for the reply!

**Comment by stefanpenner** [comment]
Will gladly reopen with an example that demonstrates :)

**Comment by martynsmith** [comment]
Okay, so it turns out this was entirely user error. I confused `es6-promise` and `promise-es6` (although to be fair, that _is_ a tad confusing).

This library is fine, the other one is exhibiting that bug, I'm just going to use this one everywhere ...

Thanks for your prompt replies though :-)

**Comment by stefanpenner** [comment]
Ah. That's crazy.

Sorry for the confusion, but glad to hear es6-promise does the trick :)
