### ISSUE TITLE
How to test on older browser?

### ISSUE THREAD

**Issue by benjiwheeler** [jakearchibald/es6-promise#117]
Any suggestions for how to test if this works on an older browser? I'm not positive i'm implementing this correctly and not causing conflicts, and don't know how to test it since all my browsers are current and have promises already...

**Comment by stefanpenner** [comment]
I can with confidence say it works on ie6 and android 2.2 and highee

**Comment by stefanpenner** [comment]
Any further requests?

**Comment by benjiwheeler** [comment]
I'm not doubting that it works, I'm doubting that I'm using it correctly!

I don't have a browser that is missing the current implementation of promises, so if I'm failing to initialize the es6-promise global correctly, and thus failing to make my site work on older browsers, how will I be able to tell that is the case?
