### ISSUE TITLE
2.2.0 release

### ISSUE THREAD

**Issue by vicb** [jakearchibald/es6-promise#119]
@jakearchibald could you please release 2.2.0 (would help with angular2). Thanks.

/ref https://github.com/jakearchibald/es6-promise/pull/116#issuecomment-105595778

**Comment by vicb** [comment]
@jakearchibald could you please take a look at this ? Thanks

**Comment by jakearchibald** [comment]
*Jake Archibald emerges from the mind-swamp of Google I/O*

Done!

*Goes back to bed*
