### ISSUE TITLE
Create release tag for 2.3.0

### ISSUE THREAD

**Issue by ebidel** [jakearchibald/es6-promise#122]
bower.json has been rev'd but there's not a tag for it.

**Comment by jakearchibald** [comment]
I've created a tag for 2.2.0, not sure if we're ready for 2.3.0 - @stefanpenner?

**Comment by ebidel** [comment]
Thanks!

**Comment by stefanpenner** [comment]
i believe we are ready for 2.3.0

**Comment by vicb** [comment]
+1 it is needed for angular - via zone.js
Thanks

**Comment by jakearchibald** [comment]
Done!

**Comment by vicb** [comment]
thanks !
