### ISSUE TITLE
Native promise check fails in Chrome (43 +)

### ISSUE THREAD

**Issue by tlconnor** [jakearchibald/es6-promise#124]
The check for a valid Promise implementation looks at ```Object.prototype.toString.call(Promise.resolve())```.

It expects the result to be ```"[object Promise]"``` however in Chrome the result will be ```"[object Object]"```.

**Comment by tlconnor** [comment]
The same issue occurs in node.js.

```
> Object.prototype.toString.call(Promise.resolve())
'[object Object]'
```

This results in the valid native promise implementation being overridden.

**Comment by stefanpenner** [comment]
This is because chromes promises are still broken
