### ISSUE TITLE
bad polyfill check

### ISSUE THREAD

**Issue by oallouch** [jakearchibald/es6-promise#132]
For the lastest version of Chrome (v44), the line 21 of polyfill.js would works if it was

if (P && Object.prototype.toString.call(P.resolve()) === '[object Object]' && !P.cast) {
instead of
if (P && Object.prototype.toString.call(P.resolve()) === '[object Promise]' && !P.cast) {

but I don't know for other browser or Chrome versions

I saw that because, when the polyfill is used, I don't get the default "Uncaught (in promise)" error logging.

Thx in Advance

Olivier Allouch
www.illicotravel.com

**Comment by stefanpenner** [comment]
duplicate

**Comment by oallouch** [comment]
oupsy !

**Comment by stefanpenner** [comment]
this does seem to be a common thing, i believe we will offer to packages to provide the behavior each user expects.
