### ISSUE TITLE
Polyfill replaces native Promise in Chrome and Safari

### ISSUE THREAD

**Issue by pornel** [jakearchibald/es6-promise#136]
Chrome (46.0.2478.0 canary (64-bit)) and Safari (8.0.7 (10600.7.12) OS X) don't pass the test in:

https://github.com/jakearchibald/es6-promise/blob/master/dist/es6-promise.js#L941-L945

```js
Object.prototype.toString.call(Promise.resolve())
```
> "[object Object]"

and get mutation observer hack instead of native promises.

**Comment by pornel** [comment]
Firefox returns `"[object Promise]"` :+1:

**Comment by stefanpenner** [comment]
duplicate, [please search existing issues](https://github.com/jakearchibald/es6-promise/search?q=%22%5Bobject+Promise%5D%22&type=Issues&utf8=%E2%9C%93)

**Comment by pornel** [comment]
I did search, but there was no *open* issue about this, and the source code doesn't have any comments indicating that it's a deliberate workaround rather than an omission.
