### ISSUE TITLE
Native Promise replaced by pollyfil in Chrome

### ISSUE THREAD

**Issue by davidtw** [jakearchibald/es6-promise#139]
Hi,

The native Promise seems to be replaced by es6-promise by default in Chrome (it's looks fine in firefox).
From what I can gather, it is due to the following test in lib$es6$promise$polyfill$$polyfill() :

Object.prototype.toString.call(P.resolve()) === '[object Promise]'

In chrome it will return '[object Object]', maybe it should be replaced by testing the type of P.resolve === 'function' or something like ?

**Comment by stefanpenner** [comment]
This is a duplicate of a closed issue. Please search before posting
