### ISSUE TITLE
Function polyfill() is always called

### ISSUE THREAD

**Issue by radarek** [jakearchibald/es6-promise#141]
README says that for global polyfill we should call:

```
require('es6-promise').polyfill();
```

[Apparently this is called by default](https://github.com/jakearchibald/es6-promise/blob/master/lib/es6-promise.umd.js#L18):

```
var originalPromise = Promise;

console.log(require('es6-promise').Promise == Promise);
console.log(originalPromise == Promise);
```

Output:
```
true
false
```

**Comment by andrewwakeling** [comment]
+1. This was happening unexpectedly to me as well.

**Comment by tomekwi** [comment]
Yeah.

I run into some [very weird problems](https://github.com/KenPowers/dr-promise/pull/1#issuecomment-142242614) letaly – and it looks like it’s [`dist/es6-promise.js`](https://github.com/jakearchibald/es6-promise/blob/v3.0.2/dist/es6-promise.js#L926-L965) that causes them.

**Comment by tomekwi** [comment]
@jakearchibald it even goes as far as overwrite the native `Promise`:

Without `es6-promise`: http://jsbin.com/jezare/1/edit?html,js,console
With `es6-promise`: http://jsbin.com/jezare/2/edit?html,js,console

**Comment by radarek** [comment]
@tomekwi I showed this behavior in my example ;) (maybe I should be more precisely).

**Comment by tomekwi** [comment]
Oh, yeah, I missed that – sorry!

**Comment by stefanpenner** [comment]
This is a dupe. Native promise in chrome still has bugs, and doesn't correctly advertise itself as the spec requires.

**Comment by tomekwi** [comment]
> Native promise in chrome still has bugs, and doesn't correctly advertise itself as the spec requires.

Seems like a n answer to

> it even goes as far as overwrite the native Promise

– but not to

> `require('es6-promise')` installs a global polyfill

It’s `require('es6-promise').polyfill()` which should install the polyfill, and `require('es6-promise')` should just return an object shouldn’t it?
