### ISSUE TITLE
Leaks Promise global in nodejs

### ISSUE THREAD

**Issue by devinivy** [jakearchibald/es6-promise#143]
This library leaks the `Promise` global when `require`d using nodejs.  Automatically creating global variables is considered a bad practice in nodejs.  Leaking global variables also makes testing suites fail, which is the main practical reason I'm reporting this.  The polyfill should probably be opt-in, at least for nodejs.  Related to #141.

**Edit** Just saw some plans around this issue in #140 too.

**Comment by stefanpenner** [comment]
> Automatically creating global variables is considered a bad practice in nodejs

Just so you are aware, this library is a polyfil. So this is working as expected. People have wanted this library to do both, so we will be providing two builds.

**Comment by devinivy** [comment]
Thanks!

**Comment by stefanpenner** [comment]
That's around for legacy reasons
