### ISSUE TITLE
[Object Promise] check is always false

### ISSUE THREAD

**Issue by marcog83** [jakearchibald/es6-promise#148]
Hi, great job
I started using this implementation because of its lightweight. When I tried it in chrome, that has native promises, I wondered why es6promise overwrote native and I saw that polyfill has this check that is always false, because chrome returns [object object]

```Object.prototype.toString.call(P.resolve()) === '[object Promise]'```

I hope it can help.
Marco

**Comment by stefanpenner** [comment]
Chromes promises are still filled with bugs. We will continue to stomp it until they are fixed.

I have actually just started fixing chromes own promises implementation. 2 merged patches accepted already afew more to go.

Anyways, we won't change the functionality here. Rather we will just keep fixing v8s until our sniffing no longer stomps it out.
