### ISSUE TITLE
Reject function does not pass on variadic arguments.

### ISSUE THREAD

**Issue by novabyte** [jakearchibald/es6-promise#150]
As a simple example:

```js
var promise = new Promise(function(resolve, reject) {
  try {
    throw new Error("Something went wrong.");
  } catch (err) {
    reject(err.message, err);
  }
}).then(function() {
}).catch(function(message, err) {
  // err is undefined!
});
```

The `reject` function does not pass on its arguments to the `catch` function - only the first argument is passed on.

Is this a bug in the library?

**Comment by stefanpenner** [comment]
> Is this a bug in the library?

nope, its part of the specification.

**Comment by novabyte** [comment]
@stefanpenner OK, what a shame. Thanks for the quick reply.
Can I ask - does RSVP support variadic arguments to the `resolve` and `reject` functions?

**Comment by stefanpenner** [comment]
> OK, what a shame. 

Nah, its not needed. ES6 destructuring has got your back and since destructing pojos is also supported, we are no longer stuck with crappy positional argument coupling.

for example:

```js
Promise.all([a, b, c]).then(([a, b, c]) => ....)
```

```js
Promise.reject({
  message: 'some message',
  reason: error
}).catch(({message}) => {
  ...
});
```

> Can I ask - does RSVP support variadic arguments to the resolve and reject functions?

Nope,  since the language has destructing it is not needed. Its true (and unfortunate) for now an additional compiler is needed. But a trade-off I consider worth-while.

**Comment by novabyte** [comment]
Thanks @stefanpenner.
I wish I could use ES6 destructuring support (reminds me of Erlang's pattern matching) but unfortunately your es6-promise library is part of a code execution cluster I've written with the Rhino JavaScript VM whose support for ES6 is limited right now.
I'll work around it or patch your es6-promise library.
