### ISSUE TITLE
Promise.flush for testing

### ISSUE THREAD

**Issue by ccorcos** [jakearchibald/es6-promise#157]
In angular, you can flush all promises to resolve immediately so you dont have to deal with deferring execution for all the async callbacks when testing async code. It would be really cool if this library offered a similar solution.

**Comment by stefanpenner** [comment]
This library offers a pluggable scheduler, where this could be accomplished via a custom scheduler. Unfortunately shipping such functionality is likely out of scope for the project.

If someone is interested in submitting an example of such scheduler for the readme. It would likely be accepted.

**Comment by ccorcos** [comment]
Hmm. So this doesnt quite work...

```js
Promise._setScheduler = function(fn) { return fn() }
console.log("a")
x = new Promise(function(resolve, reject) { resolve(10) })
x.then(function(result) { console.log("b!", result) })
console.log("c")
```

I'd hope to see "b" print before "c". Any ideas?

**Comment by stefanpenner** [comment]
that isn't flush, that is sync. Which is a different thing. For that you must use  setAsap https://github.com/jakearchibald/es6-promise/blob/master/lib/es6-promise/promise.js#L163

**Comment by ccorcos** [comment]
yeah, I agree and I'm not exacty proud of it, but we're trying to move away from angular so we're starting with the HTTP library, but angular has all these nice tools async testing by being able to flush promise resolutions and I don't want to have to rewrite hundreds of tests :/

**Comment by stefanpenner** [comment]
Understood. Hopefully the above two hooks are sufficient

**Comment by ccorcos** [comment]
Hmm. Still doesnt work:

```js
Promise._setAsap = function(fn) { return fn() }
console.log("a")
x = new Promise(function(resolve, reject) { resolve(10) })
x.then(function(result) { console.log("b!", result) })
console.log("c")
```

Looks like a bug. It appears you're trying to change it by reference:

https://github.com/jakearchibald/es6-promise/blob/master/lib/es6-promise/asap.js#L27

But you're de-referenceing it into a new variable:

https://github.com/jakearchibald/es6-promise/blob/master/lib/es6-promise/promise.js#L15

And using it directly:

https://github.com/jakearchibald/es6-promise/blob/master/lib/es6-promise/promise.js#L375

My point is, `Promise._setAsap` doesn't work.

**Comment by ccorcos** [comment]
You have a test for it though which appears to work...

https://github.com/jakearchibald/es6-promise/blob/master/test/scheduler-test.js#L56
