### ISSUE TITLE
Do not load es6-promise in Chrome where Promises are avaliable

### ISSUE THREAD

**Issue by Niondir** [jakearchibald/es6-promise#158]
In polyfill.js is a check weather the polyfill needs to be applied:
    var P = local.Promise;

    if (P && Object.prototype.toString.call(P.resolve()) === '[object Promise]' && !P.cast) {
      return;
    }

    local.Promise = Promise;

In Chrome
    Object.prototype.toString.call(window.Promise.resolve())

Returns ```"[object Object]"``` and therefor the check fails.

**Comment by stefanpenner** [comment]
This is a duplicate. TL;DR chromes promises have some gnarly bugs, I have submitted fixes to v8 itself to address them. And i believe they are working to resolve the last few.
