### ISSUE TITLE
Unhandled promise rejection error removes stack traces. Debugging is now dead in the water.

### ISSUE THREAD

**Issue by Industrial** [jakearchibald/es6-promise#164]
Hi.

Say I'm coding some site with Babel.js and React and Browserify (a common stack nowadays); Every error that I make will yield this "Unhandled promise rejection" error. Isn't the point of a promise rejection that when not handled by a `.catch()` somewhere up the line it will throw the error itself, and that you DON'T throw a generic error "uh you forgot to catch something mate" ?

This approach totally removes the stack traces from my errors and now I have to hunt my source for where the problem is every time. This is going to cost me more time then should be required for debugging and also my program/dev environment is kind of telling me that I can't make mistakes.

Is this really the desired implementation?

**Comment by stefanpenner** [comment]
this library does not log `Unhandled promise rejection`

**Comment by Industrial** [comment]
Sorry, my fault.
