### ISSUE TITLE
component.io support

### ISSUE THREAD

**Issue by RangerMauve** [jakearchibald/es6-promise#32]
It'd be nice if there was a component.json file for use with component.io. So far this is the best library for me, but it breaks my build system a little.

**Comment by stefanpenner** [comment]
i'll gladly take a PR to help improve this for you.

**Comment by RangerMauve** [comment]
Component seems to be dead now and its successor doesn't require any special file. Sorry for not closing this earlier

**Comment by stefanpenner** [comment]
@RangerMauve no problem, just doing some spring cleaning
