### ISSUE TITLE
Not resolving promises due to promises/asap length conditional

### ISSUE THREAD

**Issue by zdennis** [jakearchibald/es6-promise#74]
I opened an issue over on mozilla/localforage.js in its distribution build that relates to the `asap` function: https://github.com/mozilla/localForage/issues/338#issuecomment-69931444

The potential issue is around the conditional found [here](https://github.com/jakearchibald/es6-promise/blob/5098d9e6c9b2fc63e966094be8c3b037cc7f1f2d/lib/es6-promise/asap.js#L8-L13):

```
  if (len === 2) {
    // If len is 1, that means that we need to schedule an async flush.
    // If additional callbacks are queued before the queue is flushed, they
    // will be processed by this flush that we are scheduling.
    scheduleFlush();
  }
```

It looks like the code here changed because the comment is now out of sync with the conditional, but the conditional I believe is a bug.

The issue we're running into is that there are situations where iOS 7 will re-launch an app with previously defined callbacks/promises in the queue and a flush is never scheduled because the `len === n` check doesn't match.

By changing the conditional (or removing it altogether) everything continues to work. I'm not sure why the current length check exists, but it seems like an issue that shouldn't happen under normal conditions, but does happen in certain edge cases.

**Comment by stefanpenner** [comment]
is ios7 the one that replays the last 10 seconds when resumed? or was that ios6

**Comment by stefanpenner** [comment]
comment fixed, this unfortunately is unlikely a bug in our code...
