### ISSUE TITLE
Can't use polyfill since v2.0

### ISSUE THREAD

**Issue by mislav** [jakearchibald/es6-promise#75]
Requiring `promise.js` doesn't polyfill Promise since version 2.0 as [it seems it requires a JavaScript loader now](https://github.com/components/es6-promise/blob/b5d44f8438928feb0de681be37ab6ff9a1248c7b/promise.js#L953-L959).

Version 1.0 of the polyfill could be used as normal JavaScript:

```html
<script src=promise.js></script>
<script>new Promise</script>
```

This was broken in v2.0.

**Comment by mislav** [comment]
Are we supposed to activate the polyfill manually now?

```js
ES6Promise.polyfill()
```

This doesn't seem to be documented in the README, nor the CHANGELOG, nor is there any GitHub Relase notes https://github.com/jakearchibald/es6-promise/releases/tag/2.0.0

**Comment by andrewjmead** [comment]
+1

**Comment by splintercode** [comment]
+1 ran into this today.

**Comment by MrJH** [comment]
var Promise = Promise || ES6Promise.Promise; << this will help

**Comment by stefanpenner** [comment]
> Requiring promise.js doesn't polyfill Promise since version 2.0 as it seems it requires a JavaScript loader now.

So it doesn't require a loader, but it will use one when available. Would you prefer it always expose a global?

**Comment by stefanpenner** [comment]
this is an old version, the latest auto-polyfils https://github.com/jakearchibald/es6-promise/blob/master/lib/es6-promise.umd.js#L18

**Comment by stefanpenner** [comment]
@jakearchibald can we got another release, this is fixed on master.

**Comment by mislav** [comment]
If the library is supposed to auto-polyfill, then we'd like to have another 2.x release where this is fixed. If the decision was made to *not* auto-polyfill, then I'd like to see documentation on how to activate the polyfill ourselves. Then this issue can be closed. Thanks!

**Comment by bvaughn** [comment]
+1 for docs about the library not auto-polyfilling. Confused me for a few moments also.

**Comment by stefanpenner** [comment]
> If the library is supposed to auto-polyfill, then we'd like to have another 2.x release where this is fixed. If the decision was made to not auto-polyfill, then I'd like to see documentation on how to activate the polyfill ourselves. Then this issue can be closed. Thanks!

we auto-polyfil. @jakearchibald can we get a release this weekend?

**Comment by coderhaoxin** [comment]
is new `auto-polyfil` release ready?

**Comment by stefanpenner** [comment]
yup, pending a release. I don't think i have all the creds needed to releasing.

**Comment by jakearchibald** [comment]
Will do a release today, cheers!

**Comment by jakearchibald** [comment]
Done

**Comment by mislav** [comment]
README still instructs that we need to do `require('es6-promise').polyfill()`

**Comment by mislav** [comment]
Also, I'm trying to evaluate whether we want to upgrade v1.0.0 to v2.1.0 on GitHub.com. Since CHANGELOG has been eviscerated b301f173ec106708c769619567cf479bb7321826, could we maybe ask that release notes be added to Releases for this project? Like, which exact bugs have been fixed, in which cases is the new version more performant, etc. Thanks.

**Comment by stefanpenner** [comment]
Sure. I'll try to find more time.

The quick answer is lots of bug fixes and performance work.
