### ISSUE TITLE
Subclassing difficult

### ISSUE THREAD

**Issue by altano** [jakearchibald/es6-promise#76]
I'm having trouble subclassing es6-promise because of the internal call to the constructor inside of then():

```javascript
then: function(onFulfillment, onRejection) {
  var parent = this;
  var state = parent._state;

  if (state === $$$internal$$FULFILLED && !onFulfillment || state === $$$internal$$REJECTED && !onRejection) {
      return this;
  }

  var child = new this.constructor($$$internal$$noop); // <=========
  ...
```

This makes it so that in my subclass constructor any calls to this.catch() or this.then() will result in infinite recursion.  Is this call to the constructor necessary?

Here's some code that demonstrates the issue:

```javascript
var ES6Promise = require("es6-promise").Promise;

function StrictPromise(exec) {
    ES6Promise.call(this, exec);
    this.hasRejectionHandler = false;
    ES6Promise.prototype.then.call(this, null, this.onRejection.bind(this));
}
StrictPromise.__proto__ = ES6Promise.prototype;
StrictPromise.prototype = Object.create(ES6Promise.prototype, {
    constructor: { value: StrictPromise }
});

StrictPromise.prototype.then = function (onFulfilled, onRejected) {
    if (onRejected) {
        this.hasRejectionHandler = true;
    }
    return ES6Promise.prototype.then.apply(this, arguments);
};

StrictPromise.prototype.catch = function () {
    this.hasRejectionHandler = true;
    return ES6Promise.prototype.catch.apply(this, arguments);
};

StrictPromise.prototype.onRejection = function () {
    if (!this.hasRejectionHandler) {
        setTimeout(function () {
            // TODO ...
        }, 0);
    }
};

new StrictPromise(function (resolve, reject) {
    throw new Error("Hello");
});
```

In short, if es6-promise creates a promise in the constructor, no subclass can do the same.

**Comment by stefanpenner** [comment]
this seems expected?

**Comment by stefanpenner** [comment]
also what you are trying to add should land in es6-promise this weekend. AKA handled/unhandled rejection tracking.

**Comment by altano** [comment]
What seems expected?  It is expected that then() will create a new Promise, but it should not be expected that Promise.constructor calls then().

Or would you expect the Promise constructor to create another promise in addition to *this*?

**Comment by domenic** [comment]
Then should call this.constructor. This.constructor should not call then.

**Comment by altano** [comment]
I saw the other thread, and while a good start, "emission" means logging to the console which isn't good enough for my needs.  I need to catch unhandled rejections in unit tests and in production.

**Comment by stefanpenner** [comment]
@altano maybe i don't understand what you are trying to do, please provide a concrete example.

**Comment by altano** [comment]
Oh, of course, nevermind, I'm sorry.  I had this completely backwards, of course it is behaving exactly as expected.
