### ISSUE TITLE
require('es6-promise').Promise undefined on some systems?

### ISSUE THREAD

**Issue by habahut** [jakearchibald/es6-promise#83]
I have a program running locally and on an EC2 instance. When I use 
`var Promise = require('es6-promise').Promise`

and invoke it like this: `    return new Promise(function(resolve, reject) {... `

It works just fine on EC2 . But locally (running ubuntu 14.04) I get an 'undefined is not a function' error on that line. But when I remove the .Promise: 
`var Promise = require('es6-promise')` 

It works fine locally. Both systems are installing the package the same way with npm:
`    "es6-promises": "^1.0.10",`

I have tried uninstalling and reinstalling multiple times. Any idea what is going on here?

**Comment by stefanpenner** [comment]
woah, which version of node/npm is installed on your ubuntu mahcine?

**Comment by habahut** [comment]
on my local machine I have npm 1.4.9, and 1.3.11 on the EC2 instance

**Comment by stefanpenner** [comment]
maybe try installing a more recent npm? something in the 2.x series, ideally 2.6.x.

**Comment by habahut** [comment]
having installed 2.6.1 and reinstalling I am still having the issue

**Comment by stefanpenner** [comment]
can you do the old

```
rm -rf node_modules
npm cache clear
npm install
```

**Comment by habahut** [comment]
still didn't fix it...

**Comment by stefanpenner** [comment]
can you zip up the project and share it, I cannot reproduce.

**Comment by stefanpenner** [comment]
this seems to have gone, stale. If the above request is satisfied or some reasonable repro steps.. I will gladly look into it again
